// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 07.03.2025, 11:12:58
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["X:/sapsan/components/**/*.{vue,js,jsx,mjs,ts,tsx}","X:/sapsan/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","X:/sapsan/components/**/*.{vue,js,jsx,mjs,ts,tsx}","X:/sapsan/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","X:/sapsan/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","X:/sapsan/plugins/**/*.{js,ts,mjs}","X:/sapsan/composables/**/*.{js,ts,mjs}","X:/sapsan/utils/**/*.{js,ts,mjs}","X:/sapsan/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","X:/sapsan/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","X:/sapsan/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;